import * as cdk from "aws-cdk-lib";
import {
  AccessLogFormat,
  AuthorizationType,
  CognitoUserPoolsAuthorizer,
  Cors,
  EndpointType,
  IResource,
  LambdaIntegration,
  LogGroupLogDestination,
  MethodLoggingLevel,
  RestApi,
} from "aws-cdk-lib/aws-apigateway";
import { AdvancedSecurityMode, UserPool } from "aws-cdk-lib/aws-cognito";
import { AttributeType, Table } from "aws-cdk-lib/aws-dynamodb";
import { IFunction } from "aws-cdk-lib/aws-lambda";
import { LogGroup } from "aws-cdk-lib/aws-logs";
import { NagSuppressions } from "cdk-nag";
import { Construct } from "constructs";
import * as path from "path";
import { NodejsFunctionWithRole } from "./constructs/NodejsFunctionWithRole";

interface AddApiResourceProps {
  parentResource: IResource;
  resourceName: string;
  methods: string[];
  handler: IFunction;
  cognitoAuthorizer: CognitoUserPoolsAuthorizer;
}

export class ExampleProducerServiceStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const ordersTable = new Table(this, "OrdersTable", {
      partitionKey: {
        name: "orderId",
        type: AttributeType.STRING,
      },
    });

    const userPool = new UserPool(this, "UserPool", {
      selfSignUpEnabled: false,
      passwordPolicy: {
        minLength: 8,
        requireUppercase: true,
        requireDigits: true,
        requireSymbols: true,
      },
      advancedSecurityMode: AdvancedSecurityMode.ENFORCED,
    });

    userPool.addClient("UserPoolClient", {
      authFlows: {
        adminUserPassword: true,
        userPassword: true,
        userSrp: true,
      },
    });

    const cognitoAuthorizer = new CognitoUserPoolsAuthorizer(
      this,
      "UserPoolAuthorizer",
      {
        cognitoUserPools: [userPool],
      }
    );

    const handler = new NodejsFunctionWithRole(this, "Handler", {
      entry: `${path.resolve(
        __dirname
      )}/../lambdas/producer-service-handler/src/index.ts`,
      environment: {
        TABLE_NAME_ORDERS: ordersTable.tableName,
      },
    });

    ordersTable.grantReadWriteData(handler.executionRole);

    const logGroup = new LogGroup(this, "ApiLogs");

    const restApi = new RestApi(this, "ProducerServiceAPI", {
      restApiName: "Example Producer Service API",
      description:
        "An example of a service that produces some data that consumer service needs",
      endpointConfiguration: {
        types: [EndpointType.REGIONAL],
      },
      deployOptions: {
        tracingEnabled: true,
        accessLogDestination: new LogGroupLogDestination(logGroup),
        accessLogFormat: AccessLogFormat.jsonWithStandardFields(),
        loggingLevel: MethodLoggingLevel.INFO,
        dataTraceEnabled: true,
        metricsEnabled: true,
      },
      defaultCorsPreflightOptions: {
        allowOrigins: Cors.ALL_ORIGINS,
        allowMethods: Cors.ALL_METHODS,
        allowHeaders: Cors.DEFAULT_HEADERS,
      },
      defaultIntegration: new LambdaIntegration(handler.function),
      defaultMethodOptions: {
        authorizationType: AuthorizationType.COGNITO,
        authorizer: cognitoAuthorizer,
      },
      cloudWatchRole: true,
    });

    const ordersResource = this.addLambdaBackedEndpoint({
      parentResource: restApi.root,
      resourceName: "orders",
      methods: ["POST", "PUT", "GET"],
      handler: handler.function,
      cognitoAuthorizer,
    });

    const ordersDetailsResource = ordersResource.addResource("details");

    this.addLambdaBackedEndpoint({
      parentResource: ordersDetailsResource,
      resourceName: "{orderId}",
      methods: ["GET", "DELETE"],
      handler: handler.function,
      cognitoAuthorizer,
    });

    NagSuppressions.addResourceSuppressions(
      restApi,
      [
        {
          id: "AwsSolutions-APIG4",
          reason:
            "This API does indeed implement cognito authorization on all available methods, excluding OPTIONS, which does not traditionally need authorization.",
        },
        {
          id: "AwsSolutions-COG4",
          reason:
            "This API does indeed implement cognito authorization on all available methods, excluding OPTIONS, which does not traditionally need authorization.",
        },
        {
          id: "AwsSolutions-APIG2",
          reason:
            "Request validation is handled via internal Lambda logic provided by an easier to use framework called middy. See lambda code for validation logic.",
        },
        {
          id: "AwsSolutions-IAM4",
          reason: "This role is auto-generated by CDK for demo purposes only.",
        },
      ],
      true
    );
  }

  private addLambdaBackedEndpoint(props: AddApiResourceProps) {
    const newResource = props.parentResource.addResource(props.resourceName);

    for (const method of props.methods) {
      newResource.addMethod(method, new LambdaIntegration(props.handler), {
        authorizationType: AuthorizationType.COGNITO,
        authorizer: props.cognitoAuthorizer,
      });
    }
    return newResource;
  }
}
